apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hello-world
servers: 1
agents: 1
kubeAPI:
  hostPort: "16443"
image: rancher/k3s:v1.29.1-k3s2
ports:
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 80:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraArgs:
      - arg:  --tls-san=127.0.0.1
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
